/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MIMX9352xxxxM
package_id: MIMX9352DVUXM
mcu_data: ksdk2_0
processor_version: 0.12.3
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33}
- pin_list:
  - {pin_num: F20, peripheral: LPUART2, signal: lpuart_rx, pin_signal: UART2_RXD, FSEL1: SlOW_SLEW_RATE, DSE: NO_DRIVE}
  - {pin_num: F21, peripheral: LPUART2, signal: lpuart_tx, pin_signal: UART2_TXD, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
void BOARD_InitPins_Growup(void)
{                                
    /*!< Function assigned for the core: undefined[cm33] */
    /* LPUART2 Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_UART2_RXD__LPUART2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_UART2_TXD__LPUART2_TX, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_UART2_RXD__LPUART2_RX, 
                        IOMUXC_PAD_PD_MASK);
    IOMUXC_SetPinConfig(IOMUXC_PAD_UART2_TXD__LPUART2_TX, 
                        IOMUXC_PAD_DSE(15U));

    /* FLEXCAN2 Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO25__CAN2_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO27__CAN2_RX, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO25__CAN2_TX, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);
    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO27__CAN2_RX, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    /* IO Expander & Heater Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO09__LPI2C7_SCL, 1U);
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO08__LPI2C7_SDA, 1U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO09__LPI2C7_SCL, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_OD_MASK);
    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO08__LPI2C7_SDA, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_OD_MASK);

    /* ONBOARD ADC Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_SAI1_TXC__LPSPI1_SIN, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_SAI1_RXD0__LPSPI1_SOUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_SAI1_TXD0__LPSPI1_SCK, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_SAI1_TXC__LPSPI1_SIN, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_SAI1_RXD0__LPSPI1_SOUT, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_SAI1_TXD0__LPSPI1_SCK, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TD3__GPIO4_IO16, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TX_CTL__GPIO4_IO20, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TD2__GPIO4_IO17, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TXC__GPIO4_IO21, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TD3__GPIO4_IO16, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TX_CTL__GPIO4_IO20, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TD2__GPIO4_IO17, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TXC__GPIO4_IO21, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    /* LASER DAC Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_RD3__GPIO4_IO27, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_RD0__GPIO4_IO24, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_RD3__GPIO4_IO27, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_RD0__GPIO4_IO24, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    /* LASER SWITCH Init Pin */
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_RD1__GPIO4_IO25, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_RD2__GPIO4_IO26, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_RD1__GPIO4_IO25, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_RD2__GPIO4_IO26, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    /* PHOTO SPI Init Pin */
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO19__LPSPI5_SIN, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO20__LPSPI5_SOUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO21__LPSPI5_SCK, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO19__LPSPI5_SIN, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO20__LPSPI5_SOUT, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO21__LPSPI5_SCK, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO07__GPIO2_IO07, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TD0__GPIO4_IO19, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_ENET2_TD1__GPIO4_IO18, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO07__GPIO2_IO07, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TD0__GPIO4_IO19, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_ENET2_TD1__GPIO4_IO18, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    /* TEC Init Pin. */
    IOMUXC_SetPinMux(IOMUXC_PAD_DAP_TMS_SWDIO__GPIO3_IO29, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_DAP_TDO_TRACESWO__GPIO3_IO31, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_DAP_TDI__GPIO3_IO28, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_DAP_TCLK_SWCLK__GPIO3_IO30, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_DAP_TMS_SWDIO__GPIO3_IO29, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_DAP_TDO_TRACESWO__GPIO3_IO31, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_DAP_TDI__GPIO3_IO28, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);

    IOMUXC_SetPinConfig(IOMUXC_PAD_DAP_TCLK_SWCLK__GPIO3_IO30, 
                        IOMUXC_PAD_DSE(15U) |
                        IOMUXC_PAD_FSEL1(2U) |
                        IOMUXC_PAD_PD_MASK);
                        
}
/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: undefined[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PAD_UART2_RXD__LPUART2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_PAD_UART2_TXD__LPUART2_TX, 0U);

    IOMUXC_SetPinConfig(IOMUXC_PAD_UART2_RXD__LPUART2_RX, 
                        IOMUXC_PAD_PD_MASK);
    IOMUXC_SetPinConfig(IOMUXC_PAD_UART2_TXD__LPUART2_TX, 
                        IOMUXC_PAD_DSE(15U));
    BOARD_InitPins_Growup();
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
